# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               All Things Markdown 
tagline:             ''
description:         'All Things Markdown is a website to learn about Markdown and ways you can work with and/or use Markdown in various scenarios.'

url:                 http://akaak.github.io/AllThingsMarkdown/
baseurl:             ''
paginate:            5

github:
  repo: https://github.com/akaak/AllThingsMarkdown

# added for Jekyll v3.0
gems: [jekyll-paginate]
paginate_path: "page:num"


# About/contact
author:
  name:              AK Adapa
  url:               https://twitter.com/akadapa
  email:             akaak

# Custom vars
version:             1.0.0

theme: jekyll-theme-minimal